In [ ]:
# 1.  Write a Python program that uses the HiveQL language to create a table named "Employees" with columns for "id," "name," and "salary."
from pyhive import hive

connection = hive.Connection(host="localhost", port=10000, auth="NOSASL")
cursor = connection.cursor()

create_table_query = """
CREATE TABLE Employees (
    id INT,
    name STRING,
    salary FLOAT
)
"""

cursor.execute(create_table_query)
print("Table 'Employees' created successfully.")

cursor.close()
connection.close()

In [ ]:
# 2.  Create a Python program that retrieves records from a Hive table named "Customers" where the age is greater than 30.
from pyhive import hive

connection = hive.Connection(host="localhost", port=10000, auth="NOSASL")
cursor = connection.cursor()

select_query = """
SELECT * FROM Customers WHERE age > 30
"""

cursor.execute(select_query)
results = cursor.fetchall()

print("Records where age > 30:")
for row in results:
    print(row)

cursor.close()
connection.close()

In [ ]:
# 3.  Write a Python script that sorts records in descending order based on the "timestamp" column in a Hive table named "Logs."
from pyhive import hive

connection = hive.Connection(host="localhost", port=10000, auth="NOSASL")
cursor = connection.cursor()

sort_query = """
SELECT * FROM Logs ORDER BY timestamp DESC
"""

cursor.execute(sort_query)
results = cursor.fetchall()

print("Records sorted by timestamp in descending order:")
for row in results:
    print(row)

cursor.close()
connection.close()

In [ ]:
# 4.  Write a Python program that connects to a Hive server using PyHive library and retrieves all records from a table named "Products".
from pyhive import hive

connection = hive.Connection(host="localhost", port=10000, auth="NOSASL")
cursor = connection.cursor()

select_query = """
SELECT * FROM Products
"""

cursor.execute(select_query)
results = cursor.fetchall()

print("Records from 'Products' table:")
for row in results:
    print(row)

cursor.close()
connection.close()

In [ ]:
# 5.  Write a Python script that calculates the average salary of employees from a Hive table named "Employees".
from pyhive import hive

connection = hive.Connection(host="localhost", port=10000, auth="NOSASL")
cursor = connection.cursor()

average_salary_query = """
SELECT AVG(salary) FROM Employees
"""

cursor.execute(average_salary_query)
average_salary = cursor.fetchone()[0]

print("Average salary of employees:", average_salary)

cursor.close()
connection.close()

In [ ]:
# 6.  Implement a Python program that uses Hive partitioning to create a partitioned table named "Sales_Data" based on the "year" and "month" columns.
from pyhive import hive

connection = hive.Connection(host="localhost", port=10000, auth="NOSASL")
cursor = connection.cursor()

create_table_query = """
CREATE TABLE Sales_Data (
    id INT,
    amount FLOAT
)
PARTITIONED BY (year INT, month INT)
"""

cursor.execute(create_table_query)
print("Partitioned table 'Sales_Data' created successfully.")

cursor.close()
connection.close()

In [ ]:
# 7.  Develop a Python script that adds a new column named "email" of type string to an existing Hive table named "Employees."
from pyhive import hive

connection = hive.Connection(host="localhost", port=10000, auth="NOSASL")
cursor = connection.cursor()

alter_table_query = """
ALTER TABLE Employees ADD COLUMNS (email STRING)
"""

cursor.execute(alter_table_query)
print("Column 'email' added to 'Employees' table.")

cursor.close()
connection.close()

In [ ]:
# 8.  Create a Python program that performs an inner join between two Hive tables, "Orders" and "Customers," based on a common column.
from pyhive import hive

connection = hive.Connection(host="localhost", port=10000, auth="NOSASL")
cursor = connection.cursor()

join_query = """
SELECT * FROM Orders INNER JOIN Customers ON Orders.customer_id = Customers.customer_id
"""

cursor.execute(join_query)
results = cursor.fetchall()

print("Inner join results:")
for row in results:
    print(row)

cursor.close()
connection.close()

In [ ]:
# 9.  Implement a Python program that uses the Hive SerDe library to process JSON data stored in a Hive table named "User_Activity_Logs."
from pyhive import hive

connection = hive.Connection(host="localhost", port=10000, auth="NOSASL")
cursor = connection.cursor()

select_query = """
SELECT * FROM User_Activity_Logs
"""

cursor.execute(select_query)
results = cursor.fetchall()

print("Records from 'User_Activity_Logs' table:")
for row in results:
    print(row)

cursor.close()
connection.close()